### ISSUE TITLE
Dashboard route cannot handle refresh

### ISSUE THREAD

**Issue by amcquade** [yewyewXD/React-Amazon-Price-Tracker#1]
When refreshing on the [dashboard](https://trackerbase.herokuapp.com/dashboard) page, the following is returned: `Cannot GET /dashboard`

![image](https://user-images.githubusercontent.com/16789125/97022581-4bd12080-1522-11eb-9552-b379364b2493.png)

**Comment by yewyewXD** [comment]
Hi @amcquade ! Thank you for reporting the problem, I will solve this problem and close the issue when it's resolved.

**Comment by yewyewxd** [comment]
Found a blog that might help fix this issue
https://medium.com/superhighfives/serving-client-side-routing-with-surge-sh-7b705542cf3

**Comment by yewyewxd** [comment]
this repo will be achieved due to Amazon restrictions and Heroku limitations
